
# Site settings
title: Jskeleton
email: front-end@bq.com
description: Jskeleton is an awesome javascript framework to build large scale applications..
baseurl: ""
url: "https://jskeleton.io"


# Social user names
twitter_username: bqreaders
github_username:  bq


# Custom collections
collections:
  classes:
    output: true
    permalink: /api-reference/:path/


# Build settings
markdown: kramdown


# Sass configuration
sass:
  sass_dir: assets/css
  style: compressed


# Plugins
whitelist: []
gems:      [susy, breakpoint]


# Include files
include: ['_pages']


# Exclude files
exclude: [travis-runner.sh, bower.json, editorconfig, Gemfile, Gemfile.lock, ./**/*.scss]